### PR TITLE
Make images smaller

### PR DESCRIPTION
**Pull request by obj-obj**
This is lossless compression, so the pictures look the exact same and no data is lost compared to the jpegs

lossy compression (95% quality) makes the images 1/9th of their original size but also produces some banding

Edit: I ended up setting the quality to 99% so it's not lossless anymore, because it saved another good chunk of space and looked the same to me on a 4k monitor

### CODE REVIEW

**Comment by obj-obj** [comment]
My auto-formatter also removed a _lot_ of spaces at the ends of lines, so I guess that's a good change as well..?

**Comment by obj-obj** [comment]
Size comparisons:
image
image
image

**Comment by EminGT** [comment]
Thank you so much for taking your time, I really appreciate it. But unfortunately the browser support for avif image format is pretty bad for now. More than 1/4th of the people don't use a browser that suppors avif according to caniuse.com, and that includes the latest Microsoft Edge. So I shouldn't accept this pull request. But I really appreciate your willingness to help

**Comment by obj-obj** [comment]
> Thank you so much for taking your time, I really appreciate it. But unfortunately the browser support for avif image format is pretty bad for now. More than 1/4th of the people don't use a browser that suppors avif according to caniuse.com, and that includes the latest Microsoft Edge. So I shouldn't accept this pull request. But I really appreciate your willingness to help

@EminGT wait how does edge not support it? Isn't edge chromium?

**Comment by EminGT** [comment]
It is, but it still doesn't support it for some reason. Just tested it myself

**Comment by obj-obj** [comment]
I just tested it as well and it doesn't work, microsoft really do be throwing :(

**Comment by obj-obj** [comment]
@EminGT I forgot about this but there's a way to make images try using avif and fall back to jpeg, I remember seeing it on MDN somewhere

**Comment by obj-obj** [comment]
@EminGT ok so a different image format called JPEG-XL (which is the competitor to AVIF) can do some... interesting things

image

This isn't just near-lossless like avif either, it's completely visually lossless. However no browsers support it right now (https://caniuse.com/jpegxl), so it might be a good idea to revisit in a year or two when all major browsers have support

**Comment by EminGT** [comment]
Now that's quite interesting 👀 Looking forward to it

**Comment by obj-obj** [comment]
What
image

**Pull request closed without merging**
